[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:228 Starting new HTTP connection (1): 10.50.27.166:80
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 http://10.50.27.166:80 "POST /apiMSS/uaa/oauth/manage/login2fa HTTP/1.1" 503 194
[1m[31mERROR   [0m root:log.py:46 ç™»å½•æŠ¥é”™[Errno Expecting value] <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>openresty</center>
</body>
</html>
: 0